### ISSUE TITLE
Pie 1.0 TODO list

### ISSUE THREAD

**Issue by ohtrobinson** [piegfx/Pie#1]
This issue tracks all features that need to be added before a 1.0 release. If you see any features missing that you would like added, create an issue and tag it with 1.0.

- [ ] Texture descriptions, Texture2D, 3D, etc.
- [ ] More Draw() functions, including support for vertex buffers without indices
- [ ] Multiple VBOs/Instanced rendering support
- [ ] Render target support (very important for shadows)
- [ ] Stencil state support
- [ ] Deferred multithreaded contexts
- [ ] OpenGL custom back-buffer to allow specifying formats etc on startup.
